# -*- coding: utf-8 -*-
"""device_fingerprinting_aggregation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSiWCLRI21zgWjhWmtxk9oHDGO-eLxa1
"""

from pyspark.sql import functions as F
from pyspark.sql import DataFrame
from pyspark.sql.types import DecimalType

def process_orc_pipeline(raw_customers_df: DataFrame, raw_transactions_df: DataFrame) -> DataFrame:
    """
    End-to-end data transformation pipeline for the Organized Retail Crime (ORC) Engine.

    Transforms raw transactional and customer data, cleanses missing values,
    isolates return fraud, and applies device fingerprinting to flag compromised networks.
    """

    CRITICAL_THRESHOLD = 1000.00

    # ==========================================
    # PHASE 1: DATA CLEANSING & TRANSFORMATION
    # ==========================================

    # 1. Clean Customer Data: Standardize IDs and remove ghost devices
    clean_customers_df = raw_customers_df.withColumn(
        "Customer Id", F.trim(F.upper(F.col("Customer Id")))
    ).withColumn(
        "Device Id", F.trim(F.upper(F.col("Device Id")))
    ).filter(
        (F.col("Device Id").isNotNull()) & (F.col("Device Id") != "UNKNOWN")
    )

    # 2. Transform Transactions: Filter for returns and cast financial data
    returns_only_df = raw_transactions_df.filter(
        F.upper(F.col("Transaction_Type")).isin("RETURN", "REFUND")
    ).withColumn(
        "Customer Id", F.trim(F.upper(F.col("Customer Id")))
    ).withColumn(
        # Ensure financial amounts are clean decimals for accurate aggregation
        "Transaction_Amount", F.col("Transaction_Amount").cast(DecimalType(10, 2))
    ).withColumn(
        # If returns are stored as negative numbers in the raw data, convert to positive exposure
        "Margin Exposure", F.abs(F.col("Transaction_Amount"))
    )

    # ==========================================
    # PHASE 2: RELATIONAL MAPPING & AGGREGATION
    # ==========================================

    # 3. Join cleaned customers with their return transactions
    enriched_returns_df = returns_only_df.join(
        clean_customers_df,
        on="Customer Id",
        how="inner"
    )

    # 4. Aggregate exposure by physical hardware (Device Fingerprinting)
    device_exposure_df = enriched_returns_df.groupBy("Device Id").agg(
        F.sum("Margin Exposure").alias("Total_Device_Margin_Exposure"),
        F.countDistinct("Customer Id").alias("Connected_Account_Count")
    )

    # ==========================================
    # PHASE 3: ALERTING LOGIC & ONTOLOGY PREP
    # ==========================================

    # 5. Apply business logic to isolate critical fraud rings
    critical_devices_df = device_exposure_df.filter(
        F.col("Total_Device_Margin_Exposure") > CRITICAL_THRESHOLD
    )

    # 6. Flag the compromised networks
    flagged_devices_df = critical_devices_df.withColumn(
        "Alert",
        F.lit("CRITICAL - FREEZE REQUIRED")
    )

    # 7. Map flags back to the base Customer objects for the Workshop UI
    final_ontology_customers_df = clean_customers_df.join(
        flagged_devices_df.select("Device Id", "Total_Device_Margin_Exposure", "Alert"),
        on="Device Id",
        how="left"
    ).fillna({
        "Alert": "CLEARED",
        "Total_Device_Margin_Exposure": 0.00
    })

    return final_ontology_customers_df